### ISSUE TITLE
React intl error

### ISSUE THREAD

**Issue by jiyuujin** [jiyuujin/yuukit.me#318]
```
[React Intl] Error formatting message: "webneko_blog" for locale: "ja"
Error: Cannot format XML message without DOMParser
    at new FormatError (/Users/yuukit/project/yuukit.me/public/webpack:/lib/node_modules/intl-messageformat/lib/formatters.js:25:1)
    at formatHTMLMessage (/Users/yuukit/project/yuukit.me/public/webpack:/lib/node_modules/intl-messageformat/lib/formatters.js:279:1)
    at IntlMessageFormat.formatHTMLMessage (/Users/yuukit/project/yuukit.me/public/webpack:/lib/node_modules/intl-messageformat/lib/core.js:67:37)
    at formatMessage (/Users/yuukit/project/yuukit.me/public/webpack:/lib/node_modules/react-intl/lib/formatters/message.js:44:1)
    at map (/Users/yuukit/project/yuukit.me/public/webpack:/lib/src/components/Product/index.tsx:29:46)
    at Array.map (<anonymous>)
    at Product (/Users/yuukit/project/yuukit.me/public/webpack:/lib/src/components/Product/index.tsx:22:19)
    at processChild (/Users/yuukit/project/yuukit.me/node_modules/react-dom/cjs/react-dom-server.node.development.js:3043:14)
    at resolve (/Users/yuukit/project/yuukit.me/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (/Users/yuukit/project/yuukit.me/node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)

```

**Comment by jiyuujin** [comment]
解決済
